// SPDX-License-Identifier: GPL-3.0-only
// Generated by scripts/build-content.ts from the pinned Steel Compendium. Do not edit;
// run `pnpm content:build` and review the diff. Verified by `pnpm content:check`.
import type { ContentEntry, ContentManifest } from '../../contracts/content';

// JSON modules are typed from their literal shapes (optional keys become `?: undefined`), which
// the index-signature contract rejects; the generator has already validated every entry.
const typed = (list: unknown): ContentEntry[] => list as ContentEntry[];
import manifestJson from './manifest.json';
import abilityJson from './ability.json' with { type: 'json' };
import ancestryJson from './ancestry.json';
import careerJson from './career.json';
import chapterJson from './chapter.json';
import classJson from './class.json';
import complicationJson from './complication.json' with { type: 'json' };
import conditionJson from './condition.json';
import cultureJson from './culture.json';
import featureJson from './feature.json' with { type: 'json' };
import featureGroupJson from './feature-group.json';
import featureblockJson from './featureblock.json';
import godJson from './god.json';
import kitJson from './kit.json' with { type: 'json' };
import monsterJson from './monster.json';
import perkJson from './perk.json';
import ruleJson from './rule.json';
import saintJson from './saint.json';
import skillJson from './skill.json';
import skillGroupJson from './skill-group.json';
import statblockJson from './statblock.json';
import traitJson from './trait.json';

export const manifest: ContentManifest = manifestJson;
/** Entries grouped by their source `type`, in source-path order within each kind. */
export const byKind: Record<string, ContentEntry[]> = {
  'ability': typed(abilityJson),
  'ancestry': typed(ancestryJson),
  'career': typed(careerJson),
  'chapter': typed(chapterJson),
  'class': typed(classJson),
  'complication': typed(complicationJson),
  'condition': typed(conditionJson),
  'culture': typed(cultureJson),
  'feature': typed(featureJson),
  'feature-group': typed(featureGroupJson),
  'featureblock': typed(featureblockJson),
  'god': typed(godJson),
  'kit': typed(kitJson),
  'monster': typed(monsterJson),
  'perk': typed(perkJson),
  'rule': typed(ruleJson),
  'saint': typed(saintJson),
  'skill': typed(skillJson),
  'skill-group': typed(skillGroupJson),
  'statblock': typed(statblockJson),
  'trait': typed(traitJson),
};
/** Every entry in the snapshot, kinds in alphabetical order. */
export const entries: ContentEntry[] = Object.values(byKind).flat();
