// SPDX-License-Identifier: GPL-3.0-only
// Content snapshot contract: the shape of shared/content/compendium/** generated by
// scripts/build-content.ts from the pinned Steel Compendium. Types only, no logic.
//
// Owning specifications: docs/build/S01-content-pipeline.md,
// docs/data-architecture-spec.md#3-shared-game-content (first instance of the pack direction),
// docs/monster-catalog-spec.md#logical-records (source document record).
// Schema document for humans: shared/content/README.md.

/** A value copied verbatim from the source file's YAML frontmatter. */
export type SourceValue =
  string | number | boolean | null | SourceValue[] | { [key: string]: SourceValue };

/** The `type:` value printed in the source frontmatter (statblock, ability, trait, rule, ...). */
export type ContentKind = string;

export interface ContentEntry {
  /** Source-qualified SCC id from the frontmatter `scc:` line, e.g. `mcdm.heroes.v1/class/fury`. */
  id: string;
  /** The frontmatter `type:` value, unchanged. */
  kind: ContentKind;
  /** The frontmatter `name:` value, unchanged. */
  name: string;
  /** Repo-relative path of the verbatim Markdown file, e.g. `vendor/steel-compendium/en/unified/md/class/fury.md`. */
  sourcePath: string;
  /** Repo-relative path of the JSON twin of the same source (`en/unified/json/...`). */
  jsonPath: string;
  /** Id of the manifest selection that included this entry (why it is in the v0.01 snapshot). */
  selection: string;
  /** The complete source file, byte-exact, including its frontmatter. */
  text: string;
  /**
   * Every frontmatter field other than `name`, `scc` and `type`, copied without renaming, defaulting
   * or projection. A field absent here is absent in the source; `{}` means the source states none.
   */
  structured: Record<string, SourceValue>;
  /**
   * Stat blocks only: the `features` array of the JSON twin, copied verbatim. The Markdown frontmatter
   * of a stat block does not list its embedded abilities and traits; this is the source's own
   * structured record of them (docs/monster-catalog-spec.md#features-and-supporting-rules). Absent
   * for every other kind and when the twin states no features.
   */
  features?: SourceValue[];
}

/** A manifest row describing an included entry without its text. */
export interface ManifestEntry {
  id: string;
  kind: ContentKind;
  name: string;
  sourcePath: string;
  selection: string;
  /** File under `shared/content/compendium/` that holds the full entry. */
  file: string;
}

export interface ManifestSelection {
  id: string;
  /** What the slice asked for and where the pipeline looked. */
  description: string;
  /** Source paths (relative to `en/unified/md`) or directories that were read for this selection. */
  paths: string[];
  /** Source statement that grounds the selection when it is not a plain "the slice names this path". */
  basis?: string;
}

export interface ManifestExclusion {
  /** Path relative to `en/unified/md`. */
  path: string;
  scc?: string;
  reason: string;
}

export interface ManifestGap {
  topic: string;
  note: string;
}

export interface ContentManifest {
  schemaVersion: string;
  compendium: {
    /** Submodule commit the snapshot was generated from; must equal `git submodule status`. */
    revision: string;
    /** Upstream tag at that commit when one matches, else null. */
    tag: string | null;
    /** Commit date of that revision (ISO 8601), read from the submodule. */
    committedAt: string;
    submodulePath: string;
  };
  generator: { script: string; version: string };
  /** Calendar date (YYYY-MM-DD) of the last generation whose content differed from the previous one. */
  generatedAt: string;
  /** SHA-256 over everything in the snapshot except `generatedAt`; changes whenever any entry changes. */
  contentHash: string;
  entryCount: number;
  selections: ManifestSelection[];
  entries: ManifestEntry[];
  excluded: ManifestExclusion[];
  gaps: ManifestGap[];
}
