// SPDX-License-Identifier: GPL-3.0-only
/** Printed level-one portfolio options. Stamina is per minion; R refers to the summoner. */
export const SUMMONER_MINIONS = [
  {
    name: 'Archer Spittlich',
    circle: 'Blight',
    family: 'demon',
    sourcePath: 'en/unified/md/monster/minion/summoner/demon/statblock/archer-spittlich.md',
    cost: 3,
    count: 2,
    stamina: 5,
    stability: 2,
    size: '1S',
    speed: 5,
    movement: '—',
    freeStrike: 5,
    immunities: [],
    weaknesses: ['Holy 1'],
    characteristics: {
      M: 0,
      A: 2,
      R: -1,
      I: -1,
      P: 0,
    },
    text: "These minor demons resemble larger pitlings. They can spit a nerve-numbing phlegm at long distance that makes it easy to catch their next meal.\n\n| Abyssal, Demon | - | - | Minion Artillery | 3 essence for two minions |\n|:----------------:|:--------------:|:----------------:|:-:|:-------------------------:|\n| **1S**<br>Size | **5**<br>Speed | **5 \\| 5**<br>Stamina | **2**<br>Stability | **5**<br>Free Strike |\n| **—**<br>Immunity | **—**<br>Movement | - | **Holy 1**<br>Weakness | **Poison**<br>Free Strike Damage Type |\n| **0**<br>Might | **+2**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **0**<br>Presence |\n\n> ⭐️ **Splash Strike**\n>\n> The spittlich's ranged [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) have a distance of 10 and deal 2 poison damage to an enemy adjacent to the target. Creatures that take poison damage from this spittlich can't [shift](scc.v1:mcdm.heroes.v1/movement/shifting) until the start of the spittlich's next turn.\n\n> ⭐️ **Soulsight**\n>\n> Each creature adjacent to the spittlich can't be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) from them.",
    traits: ['Splash Strike', 'Soulsight'],
  },
  {
    name: 'Ensnarer',
    circle: 'Blight',
    family: 'demon',
    sourcePath: 'en/unified/md/monster/minion/summoner/demon/statblock/ensnarer.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1M',
    speed: 5,
    movement: '—',
    freeStrike: 2,
    immunities: [],
    weaknesses: ['Holy 1'],
    characteristics: {
      M: 2,
      A: 0,
      R: -1,
      I: -1,
      P: -1,
    },
    text: "This vaguely humanoid form is warped and distorted by a demon nestled inside them. They extend long tongues from multiple orifices to drag victims in close.\n\n| Abyssal, Demon | - | - | Signature Minion Brute | 1 essence per minion summoned |\n|:--------:|:--------------:|:----------------------:|:-:|:-----------------------------:|\n| **1M**<br>Size | **5**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **2**<br>Free Strike |\n| **—**<br>Immunity | **—**<br>Movement | - | **Holy 1**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **0**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **-1**<br>Presence |\n\n> ⭐️ **Extended Barbed Strike**\n>\n> The ensnarer's melee [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) have a distance of 3 and inflict [pull](scc.v1:mcdm.heroes.v1/movement/forced-movement) 1. The [pull](scc.v1:mcdm.heroes.v1/movement/forced-movement) distance increases by 1 for each additional ensnarer striking the same target. Choose the ensnarer that the target is being pulled to before applying [forced movement](scc.v1:mcdm.heroes.v1/movement/forced-movement).\n\n> ⭐️ **Soulsight**\n>\n> Each creature adjacent to the ensnarer can't be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) from them.",
    traits: ['Extended Barbed Strike', 'Soulsight'],
  },
  {
    name: 'Fanged Musilex',
    circle: 'Blight',
    family: 'demon',
    sourcePath: 'en/unified/md/monster/minion/summoner/demon/statblock/fanged-musilex.md',
    cost: 3,
    count: 2,
    stamina: 6,
    stability: 1,
    size: '1L',
    speed: 6,
    movement: '—',
    freeStrike: 5,
    immunities: [],
    weaknesses: ['Holy 1'],
    characteristics: {
      M: 2,
      A: 1,
      R: -1,
      I: -1,
      P: 0,
    },
    text: "Ensnarers knot and twist their bodies together to form heaving, heavy musilexes. They're compelled to drag everything in toward their body.\n\n| Abyssal, Demon | - | - | Minion Brute | 3 essence for two minions |\n|:--------------:|:--------------:|:------------:|:-:|:-------------------------:|\n| **1L**<br>Size | **6**<br>Speed | **6 \\| 6**<br>Stamina | **1**<br>Stability | **5**<br>Free Strike |\n| **—**<br>Immunity | **—**<br>Movement | - | **Holy 1**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **+1**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **0**<br>Presence |\n\n> ⭐️ **Mawful Strike**\n>\n> The musilex's melee [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) have a distance of 2 + R and inflict [pull](scc.v1:mcdm.heroes.v1/movement/forced-movement) 2. The [pull](scc.v1:mcdm.heroes.v1/movement/forced-movement) distance increases by 2 for each additional musilex striking the same target. Choose the musilex that the target is being pulled to before applying [forced movement](scc.v1:mcdm.heroes.v1/movement/forced-movement). If the target is pulled adjacent to the musilex, the musilex either deals an additional 2 damage or [grabs](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/grab) them.\n\n> ⭐️ **Soulsight**\n>\n> Each creature adjacent to the musilex can't be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) from them.",
    traits: ['Mawful Strike', 'Soulsight'],
  },
  {
    name: 'Rasquine',
    circle: 'Blight',
    family: 'demon',
    sourcePath: 'en/unified/md/monster/minion/summoner/demon/statblock/rasquine.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1S',
    speed: 4,
    movement: 'Teleport',
    freeStrike: 2,
    immunities: [],
    weaknesses: ['Holy 1'],
    characteristics: {
      M: -1,
      A: 0,
      R: -1,
      I: -1,
      P: 2,
    },
    text: "The rasquine are skulking demons that shimmer in the light. They teleport into position before biting the necks of their prey.\n\n| Abyssal, Demon | - | - | Signature Minion Ambusher | 1 essence per minion summoned |\n|:--------:|:--------------:|:-------------------------:|:-:|:-----------------------------:|\n| **1S**<br>Size | **4**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **2**<br>Free Strike |\n| **—**<br>Immunity | **Teleport**<br>Movement | - | **Holy 1**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **-1**<br>Might | **0**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Skulker**\n>\n> Once per turn, the rasquine can [hide](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) as a [free maneuver](scc.v1:mcdm.heroes.v1/rule.combat/free-maneuver) after [teleporting](scc.v1:mcdm.heroes.v1/movement/teleport).\n\n> ⭐️ **Soulsight**\n>\n> Each creature adjacent to the rasquine can't be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) from them.",
    traits: ['Skulker', 'Soulsight'],
  },
  {
    name: 'Razor',
    circle: 'Blight',
    family: 'demon',
    sourcePath: 'en/unified/md/monster/minion/summoner/demon/statblock/razor.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1M',
    speed: 6,
    movement: '—',
    freeStrike: 1,
    immunities: [],
    weaknesses: ['Holy 1'],
    characteristics: {
      M: 0,
      A: 2,
      R: -1,
      I: -1,
      P: -1,
    },
    text: "Razors appear to be a diminutive variant of the ruinant demon. Their bodies are swift, tumbling mounds of scarred flesh and deadly claws.\n\n| Abyssal, Demon | - | - | Signature Minion Harrier | 1 essence per minion summoned |\n|:-----:|:--------------:|:------------------------:|:-:|:-----------------------------:|\n| **1M**<br>Size | **6**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **—**<br>Immunity | **—**<br>Movement | - | **Holy 1**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **0**<br>Might | **+2**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **-1**<br>Presence |\n\n> ⭐️ **Teeth!**\n>\n> Once per turn, whenever an adjacent enemy [grabs](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/grab) the razor or uses a melee ability against them, that enemy takes 1 damage for each razor adjacent to them.\n\n> ⭐️ **Soulsight**\n>\n> Each creature adjacent to the razor can't be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) from them.",
    traits: ['Teeth!', 'Soulsight'],
  },
  {
    name: 'Twisted Bengrul',
    circle: 'Blight',
    family: 'demon',
    sourcePath: 'en/unified/md/monster/minion/summoner/demon/statblock/twisted-bengrul.md',
    cost: 3,
    count: 2,
    stamina: 5,
    stability: 1,
    size: '1L',
    speed: 5,
    movement: '—',
    freeStrike: 4,
    immunities: [],
    weaknesses: ['Holy 1'],
    characteristics: {
      M: 2,
      A: 1,
      R: -1,
      I: -1,
      P: 0,
    },
    text: "The bengrul is an undulating heap of glass and flesh. They shatter pieces of themselves to disrupt senses and inflict grisly wounds on their prey.\n\n| Abyssal, Demon | - | - | Minion Hexer | 3 essence for two minions |\n|:---------------:|:--------------:|:------------:|:-:|:-------------------------:|\n| **1L**<br>Size | **5**<br>Speed | **5 \\| 5**<br>Stamina | **1**<br>Stability | **4**<br>Free Strike |\n| **—**<br>Immunity | **—**<br>Movement | - | **Holy 1**<br>Weakness | **Psychic**<br>Free Strike Damage Type |\n| **+2**<br>Might | **+1**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **0**<br>Presence |\n\n> 🏹 **Mind Twist 2d10 + R (Signature Ability)**\n>\n> | **Magic, Ranged, Strike** | **[Main action](scc.v1:mcdm.heroes.v1/rule.combat/turn)** |\n> |---------------------------|----------------:|\n> | **📏 Ranged 5** | **🎯 One creature or object per minion** |\n>\n> 4 damage; P < WEAK twisted (save ends)\n>\n> 6 damage; P < AVERAGE twisted (save ends)\n>\n> 8 damage; P < STRONG twisted (save ends)\n>\n> **Effect:** A twisted target can't take advantage of [edges](scc.v1:mcdm.heroes.v1/rule.dice/edge) or [search for hidden creatures](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/search-for-hidden-creatures) until the condition ends.\n\n> ⭐️ **Soulsight**\n>\n> Each creature adjacent to the ensnarer can't be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) from them.",
    traits: ['Mind Twist 2d10 + R (Signature Ability)', 'Soulsight'],
  },
  {
    name: 'Grave Knight',
    circle: 'Graves',
    family: 'undead',
    sourcePath: 'en/unified/md/monster/minion/summoner/undead/statblock/grave-knight.md',
    cost: 3,
    count: 2,
    stamina: 6,
    stability: 1,
    size: '1M',
    speed: 6,
    movement: '—',
    freeStrike: 5,
    immunities: ['Corruption R', 'Poison R'],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: 1,
      R: 0,
      I: 0,
      P: 1,
    },
    text: "The grave knights are zombie warriors that continue to fight after death. Any blood spilled at a grave knight's hand runs pitch black.\n\n| Undead | - | - | Minion Brute | 3 essence for two minions |\n|:------------:|:------:|:------------:|:-:|:-------------------------:|\n| **1M**<br>Size | **6**<br>Speed | **6 \\| 6**<br>Stamina | **1**<br>Stability | **5**<br>Free Strike |\n| **Corruption R, Poison R**<br>Immunity | **—**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **+1**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+1**<br>Presence |\n\n> 🏹 **Knight Strike 2d10 + R (Signature Ability)**\n>\n> | **Melee, Strike, Weapon** | **[Main action](scc.v1:mcdm.heroes.v1/rule.combat/turn)** |\n> |---------------------------|----------------:|\n> | **📏 Melee 1** | **🎯 One creature or object per minion** |\n>\n> 5 corruption damage; M < WEAK [bleeding](scc.v1:mcdm.heroes.v1/condition/bleeding) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn))\n>\n> 7 corruption damage; M < AVERAGE [bleeding](scc.v1:mcdm.heroes.v1/condition/bleeding) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn))\n>\n> 9 corruption damage; M < STRONG [bleeding](scc.v1:mcdm.heroes.v1/condition/bleeding) (save ends)\n\n> ⭐️ **To the Grave**\n>\n> When the grave knight is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), they can make a melee [free strike](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) before being destroyed.",
    traits: ['Knight Strike 2d10 + R (Signature Ability)', 'To the Grave'],
  },
  {
    name: 'Husk',
    circle: 'Graves',
    family: 'undead',
    sourcePath: 'en/unified/md/monster/minion/summoner/undead/statblock/husk.md',
    cost: 1,
    count: 1,
    stamina: 3,
    stability: 1,
    size: '1M',
    speed: 5,
    movement: '—',
    freeStrike: 1,
    immunities: ['Damage 2', 'Corruption R', 'Poison R'],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: 0,
      R: -1,
      I: -1,
      P: -1,
    },
    text: "Husks have stiff corpses that snap and crackle with each sudden movement. Corrosive breath endlessly billows from their slackjawed faces.\n\n| Undead | - | - | Signature Minion Defender | 1 essence per minion summoned |\n|:----:|:------:|:-------------------------:|:-:|:-----------------------------:|\n| **1M**<br>Size | **5**<br>Speed | **3**<br>Stamina | **1**<br>Stability | **1**<br>Free Strike |\n| **Damage 2, Corruption R, Poison R**<br>Immunity | **—**<br>Movement | - | **—**<br>Weakness | **Corruption**<br>Free Strike Damage Type |\n| **+2**<br>Might | **0**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **-1**<br>Presence |\n\n> ⭐️ **Rotting Strike**\n>\n> The husk's melee [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) inflict M < WEAK [slowed](scc.v1:mcdm.heroes.v1/condition/slowed) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn)). The [potency](scc.v1:mcdm.heroes.v1/rule.character/potency) increases by 1 for each additional husk adjacent to the target (maximum +2).",
    traits: ['Rotting Strike'],
  },
  {
    name: 'Shrieker',
    circle: 'Graves',
    family: 'undead',
    sourcePath: 'en/unified/md/monster/minion/summoner/undead/statblock/shrieker.md',
    cost: 1,
    count: 1,
    stamina: 1,
    stability: 0,
    size: '1M',
    speed: 4,
    movement: '—',
    freeStrike: 2,
    immunities: ['Corruption R', 'Poison R'],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: -2,
      R: 0,
      I: 0,
      P: 2,
    },
    text: "The shrieker expresses their unending pain in a way that can be heard and felt for miles. A white-hot fire smolders within each of their sunken eye sockets.\n\n| Undead | - | - | Signature Minion Artillery | 1 essence per minion summoned |\n|:--------:|:------:|:---------------------------:|:-:|:-----------------------------:|\n| **1M**<br>Size | **4**<br>Speed | **1**<br>Stamina | **0**<br>Stability | **2**<br>Free Strike |\n| **Corruption R, Poison R**<br>Immunity | **—**<br>Movement | - | **—**<br>Weakness | **Sonic**<br>Free Strike Damage Type |\n| **-2**<br>Might | **-2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Howling Strike**\n>\n> The shrieker's ranged [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) have a distance of 12.\n\n> ⭐️ **Shrill Alarm**\n>\n> Each enemy within 2 squares of the shrieker can't [hide](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) or be [hidden](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide).",
    traits: ['Howling Strike', 'Shrill Alarm'],
  },
  {
    name: 'Skeleton',
    circle: 'Graves',
    family: 'undead',
    sourcePath: 'en/unified/md/monster/minion/summoner/undead/statblock/skeleton.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1M',
    speed: 6,
    movement: '—',
    freeStrike: 1,
    immunities: ['Corruption R', 'Poison R'],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: 0,
      R: -1,
      I: -1,
      P: -1,
    },
    text: 'These autonomous bone networks fall just short of replicating the structure they had in life. Skeleton bones are especially brittle and can splinter into huge shards when met with enough force.\n\n| Undead | - | - | Signature Minion Harrier | 1 essence per minion summoned |\n|:--------:|:------:|:-------------------------:|:-:|:-----------------------------:|\n| **1M**<br>Size | **6**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **Corruption R, Poison R**<br>Immunity | **—**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **0**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **-1**<br>Presence |\n\n> ⭐️ **Bonetrops**\n>\n> When the skeleton is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), their square becomes [difficult terrain](scc.v1:mcdm.heroes.v1/movement/difficult-terrain) for enemies. The first time any enemy enters this space, they take 2 damage and end this effect.',
    traits: ['Bonetrops'],
  },
  {
    name: 'Stalker Shade',
    circle: 'Graves',
    family: 'undead',
    sourcePath: 'en/unified/md/monster/minion/summoner/undead/statblock/stalker-shade.md',
    cost: 3,
    count: 2,
    stamina: 6,
    stability: 1,
    size: '1M',
    speed: 5,
    movement: 'Fly, hover',
    freeStrike: 5,
    immunities: ['Corruption R', 'Poison R'],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: 1,
      R: 0,
      I: 0,
      P: 2,
    },
    text: "Shades are a form of umbral stalker that float free from any floor or surface. They can bend their appearance to completely vanish in the light.\n\n| Undead | - | - | Minion Ambusher | 3 essence for two minions |\n|:-------------:|:------:|:---------------:|:-:|:-------------------------:|\n| **1M**<br>Size | **5**<br>Speed | **6 \\| 6**<br>Stamina | **1**<br>Stability | **5**<br>Free Strike |\n| **Corruption R, Poison R**<br>Immunity | **Fly, hover**<br>Movement | - | **—**<br>Weakness | **Corruption**<br>Free Strike Damage Type |\n| **-2**<br>Might | **+1**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Shadow Strike**\n>\n> The stalker shade turns invisible, [shifts](scc.v1:mcdm.heroes.v1/movement/shifting) 3 squares, and reappears after making a [strike](scc.v1:mcdm.heroes.v1/rule.combat/strike).\n\n> ⭐️ **Shadow Phasing**\n>\n> The stalker shade can move through other creatures and objects at normal speed. The first time in a round that the stalker shade passes through a creature, that creature takes 2 corruption damage. The stalker shade doesn't take damage from being [force moved](scc.v1:mcdm.heroes.v1/movement/forced-movement) into objects.",
    traits: ['Shadow Strike', 'Shadow Phasing'],
  },
  {
    name: 'Zombie Lumberer',
    circle: 'Graves',
    family: 'undead',
    sourcePath: 'en/unified/md/monster/minion/summoner/undead/statblock/zombie-lumberer.md',
    cost: 3,
    count: 2,
    stamina: 8,
    stability: 'R',
    size: '2',
    speed: 5,
    movement: '—',
    freeStrike: 1,
    immunities: ['Corruption R', 'Poison R'],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: -2,
      R: 0,
      I: 0,
      P: 1,
    },
    text: "These massive, animated ogre corpses still maintain their incredible grip strength. When a lumberer falls, they'll take anything within reach down with them.\n\n| Undead | - | - | Minion Defender | 3 essence for two minions |\n|:---------------:|:------:|:---------------:|:-:|:-------------------------:|\n| **2**<br>Size | **5**<br>Speed | **8 \\| 8**<br>Stamina | **R**<br>Stability | **1**<br>Free Strike |\n| **Corruption R, Poison R**<br>Immunity | **—**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **-2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+1**<br>Presence |\n\n> ⭐️ **Zombie Clutch**\n>\n> The lumberer's melee [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) inflict A < AVERAGE [grabbed](scc.v1:mcdm.heroes.v1/condition/grabbed). A creature or object that starts their turn [grabbed](scc.v1:mcdm.heroes.v1/condition/grabbed) by the lumberer takes corruption damage equal to your [Reason](scc.v1:mcdm.heroes.v1/rule.character/reason).\n\n> ⭐️ **Death Grasp**\n>\n> When the lumberer is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), they can latch onto an adjacent enemy before being destroyed. The enemy is M < STRONG [restrained](scc.v1:mcdm.heroes.v1/condition/restrained) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn)).",
    traits: ['Zombie Clutch', 'Death Grasp'],
  },
  {
    name: 'Nixie Soakreed',
    circle: 'Spring',
    family: 'fey',
    sourcePath: 'en/unified/md/monster/minion/summoner/fey/statblock/nixie-soakreed.md',
    cost: 1,
    count: 1,
    stamina: 1,
    stability: 0,
    size: '1T',
    speed: 5,
    movement: 'Swim',
    freeStrike: 1,
    immunities: [],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: -1,
      R: 0,
      I: 2,
      P: 1,
    },
    text: "These nixies are especially tiny. Their hair grows longer than their bodies and curls into reeds. The water soakreeds swim in tends to turn thick and cling to surfaces.\n\n| Fey | - | - | Signature Minion Controller | 1 essence per minion summoned |\n|:--------------:|:---:|:---------------------------:|:-:|:-----------------------------:|\n| **1T**<br>Size | **5**<br>Speed | **1**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **—**<br>Immunity | **Swim**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **-2**<br>Might | **-1**<br>Agility | **0**<br>Reason | **+2**<br>Intuition | **+1**<br>Presence |\n\n> ⭐️ **Water Weird**\n>\n> Once per turn during their move action, each nixie under your control can [teleport](scc.v1:mcdm.heroes.v1/movement/teleport) to a body of water within 5. The soakreed can't [teleport](scc.v1:mcdm.heroes.v1/movement/teleport) into water created by their own soaking bog.\n\n> ⭐️ **Soaking Bog**\n>\n> The area within 1 square of the soakreed is filled with swampy water. An enemy that starts their turn in the area is A < WEAK [slowed](scc.v1:mcdm.heroes.v1/condition/slowed) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn)). The [potency](scc.v1:mcdm.heroes.v1/rule.character/potency) increases by 1 for each additional soaking bog the target occupies (maximum +2).\n\n> ⭐️ **Minuscule**\n>\n> The soakreed has [cover](scc.v1:mcdm.heroes.v1/rule.combat/cover) while occupying a larger creature's space.",
    traits: ['Water Weird', 'Soaking Bog', 'Minuscule'],
  },
  {
    name: 'Pixie Bellringer',
    circle: 'Spring',
    family: 'fey',
    sourcePath: 'en/unified/md/monster/minion/summoner/fey/statblock/pixie-bellringer.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1T',
    speed: 5,
    movement: 'Fly, hover',
    freeStrike: 1,
    immunities: [],
    weaknesses: [],
    characteristics: {
      M: -3,
      A: 1,
      R: 0,
      I: 0,
      P: 2,
    },
    text: "The bellringers are glowing pixies that jingle as they fly. Historically, these pixies worked alongside bowman to ensure their arrows struck true.\n\n| Fey | - | - | Signature Minion Support | 1 essence per minion summoned |\n|:----------------:|:---:|:------------------------:|:-:|:-----------------------------:|\n| **1T**<br>Size | **5**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **—**<br>Immunity | **Fly, hover**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **-3**<br>Might | **+1**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Ringing Strike**\n>\n> The bellringer's [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) grant an [edge](scc.v1:mcdm.heroes.v1/rule.dice/edge) to the next [strike](scc.v1:mcdm.heroes.v1/rule.combat/strike) made against the target, or a double [edge](scc.v1:mcdm.heroes.v1/rule.dice/edge) if two or more bellringers strike the same target.\n\n> ⭐️ **Fairy Chime**\n>\n> Each ally within 1 square of a bellringer has a +1 to [saving throws](scc.v1:mcdm.heroes.v1/rule.general/saving-throw). Each enemy within 1 square of a bellringer has a -1 to [saving throws](scc.v1:mcdm.heroes.v1/rule.general/saving-throw).\n\n> ⭐️ **Minuscule**\n>\n> The bellringer has [cover](scc.v1:mcdm.heroes.v1/rule.combat/cover) while occupying a larger creature's space.",
    traits: ['Ringing Strike', 'Fairy Chime', 'Minuscule'],
  },
  {
    name: 'Pixie Hydrain',
    circle: 'Spring',
    family: 'fey',
    sourcePath: 'en/unified/md/monster/minion/summoner/fey/statblock/pixie-hydrain.md',
    cost: 3,
    count: 2,
    stamina: 5,
    stability: 0,
    size: '1T',
    speed: 5,
    movement: 'Fly, hover',
    freeStrike: 5,
    immunities: ['Acid R'],
    weaknesses: [],
    characteristics: {
      M: -3,
      A: 0,
      R: 1,
      I: 0,
      P: 2,
    },
    text: "This pixie flies on a delicate array of vibrant flower petals for wings. The color drains from their wings as they call forth acid rain showers.\n\n| Fey | - | - | Minion Artillery | 3 essence for two minions |\n|:-------------:|:---:|:----------------:|:-:|:-------------------------:|\n| **1T**<br>Size | **5**<br>Speed | **5 \\| 5**<br>Stamina | **0**<br>Stability | **5**<br>Free Strike |\n| **Acid R**<br>Immunity | **Fly, hover**<br>Movement | - | **—**<br>Weakness | **Acid**<br>Free Strike Damage Type |\n| **-3**<br>Might | **0**<br>Agility | **+1**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> 🏹 **Burning/Healing Rain 2d10 + R (Signature Ability)**\n>\n> | **Magic, Ranged, Strike** | **[Main action](scc.v1:mcdm.heroes.v1/rule.combat/turn)** |\n> |---------------------------|----------------:|\n> | **📏 Ranged 5** | **🎯 One creature or object per minion** |\n>\n> 5 acid damage; M < WEAK [weakened](scc.v1:mcdm.heroes.v1/condition/weakened) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn))\n>\n> 7 acid damage; M < AVERAGE [weakened](scc.v1:mcdm.heroes.v1/condition/weakened) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn))\n>\n> 9 acid damage; M < STRONG [weakened](scc.v1:mcdm.heroes.v1/condition/weakened) (save ends)\n>\n> **Effect:** After the hydrain's squad uses this ability, you or one ally within distance can spend a [Recovery](scc.v1:mcdm.heroes.v1/rule.health/recoveries) or end a [condition](scc.v1:mcdm.heroes.v1/rule.combat/condition).\n\n> ⭐️ **Minuscule**\n>\n> The hydrain has [cover](scc.v1:mcdm.heroes.v1/rule.combat/cover) while occupying a larger creature's space.",
    traits: ['Burning/Healing Rain 2d10 + R (Signature Ability)', 'Minuscule'],
  },
  {
    name: 'Pixie Loftlilly',
    circle: 'Spring',
    family: 'fey',
    sourcePath: 'en/unified/md/monster/minion/summoner/fey/statblock/pixie-loftlilly.md',
    cost: 3,
    count: 2,
    stamina: 5,
    stability: 0,
    size: '1T',
    speed: 5,
    movement: 'Fly, hover',
    freeStrike: 4,
    immunities: ['Poison R'],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: 1,
      R: 0,
      I: 0,
      P: 2,
    },
    text: "Loftlillies lazily drift through the air in flower cups. They sip on toxic nectar to emit a powerful haze from their skin.\n\n| Fey | - | - | Minion Controller | 3 essence for two minions |\n|:---------------:|:---:|:-----------------:|:-:|:-------------------------:|\n| **1T**<br>Size | **5**<br>Speed | **5 \\| 5**<br>Stamina | **0**<br>Stability | **4**<br>Free Strike |\n| **Poison R**<br>Immunity | **Fly, hover**<br>Movement | - | **—**<br>Weakness | **Poison**<br>Free Strike Damage Type |\n| **-2**<br>Might | **+1**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Floating Toxins**\n>\n> The area within 1 square of the loftlilly causes each enemy and object with a size equal to your [Reason](scc.v1:mcdm.heroes.v1/rule.character/reason) or smaller to float 1 square off the ground until they leave the area. A floating enemy that can't [fly](scc.v1:mcdm.heroes.v1/movement/fly) is unable to [shift](scc.v1:mcdm.heroes.v1/movement/shifting), moves 2 additional squares from [forced movement](scc.v1:mcdm.heroes.v1/movement/forced-movement), and has a [bane](scc.v1:mcdm.heroes.v1/rule.dice/bane) on [strikes](scc.v1:mcdm.heroes.v1/rule.combat/strike).\n\n> ⭐️ **Minuscule**\n>\n> The loftlilly has [cover](scc.v1:mcdm.heroes.v1/rule.combat/cover) while occupying a larger creature's space.",
    traits: ['Floating Toxins', 'Minuscule'],
  },
  {
    name: 'Sprite Dandeknight',
    circle: 'Spring',
    family: 'fey',
    sourcePath: 'en/unified/md/monster/minion/summoner/fey/statblock/sprite-dandeknight.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1T',
    speed: 6,
    movement: 'Fly',
    freeStrike: 1,
    immunities: [],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: 0,
      R: -1,
      I: -1,
      P: -1,
    },
    text: "Dandeknights are sprite warriors whose dragonfly wingbeats emit a tonal drone. They're usually clad in tassels that shift color as they swing their weapons.\n\n| Fey | - | - | Signature Minion Harrier | 1 essence per minion summoned |\n|:-----------------:|:---:|:------------------------:|:-:|:-----------------------------:|\n| **1T**<br>Size | **6**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **—**<br>Immunity | **Fly**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **0**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **-1**<br>Presence |\n\n> ⭐️ **Magic Strike**\n>\n> When the dandeknight strikes, you can choose one of the following damage types: acid, cold, corruption, fire, lightning, poison, or sonic. The strike deals that damage.\n\n> ⭐️ **Staccato Swings**\n>\n> When the dandeknight makes a [free strike](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike), they can make two [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) instead. The damage is added together and treated as a single [strike](scc.v1:mcdm.heroes.v1/rule.combat/strike) if both strikes hit the same target.\n\n> ⭐️ **Minuscule**\n>\n> The dandeknight has [cover](scc.v1:mcdm.heroes.v1/rule.combat/cover) while occupying a larger creature's space.",
    traits: ['Magic Strike', 'Staccato Swings', 'Minuscule'],
  },
  {
    name: 'Sprite Orchiguard',
    circle: 'Spring',
    family: 'fey',
    sourcePath: 'en/unified/md/monster/minion/summoner/fey/statblock/sprite-orchiguard.md',
    cost: 3,
    count: 2,
    stamina: 8,
    stability: 2,
    size: '1S',
    speed: 6,
    movement: 'Fly',
    freeStrike: 4,
    immunities: [],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: 0,
      R: -1,
      I: -1,
      P: -1,
    },
    text: "The orchiguard is a sprite surrounded by a wheel of shields. They are usually crushed by the pressures of their own impenetrable defenses before ever being felled by enemy hands.\n\n| Fey | - | - | Minion Defender | 3 essence for two minions |\n|:-----------------:|:---:|:---------------:|:-:|:-------------------------:|\n| **1S**<br>Size | **6**<br>Speed | **8 \\| 8**<br>Stamina | **2**<br>Stability | **4**<br>Free Strike |\n| **—**<br>Immunity | **Fly**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **0**<br>Agility | **-1**<br>Reason | **-1**<br>Intuition | **-1**<br>Presence |\n\n> ⭐️ **Fairy Guard**\n>\n> Each non-orchiguard ally takes half damage from abilities while within 1 square of the orchiguard. Whenever the orchiguard reduces damage this way, they take damage equal to half their maximum [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina) and their [free strike](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) damage increases by 1.\n\n> ⭐️ **Minuscule**\n>\n> The orchiguard has [cover](scc.v1:mcdm.heroes.v1/rule.combat/cover) while occupying a larger creature's space.",
    traits: ['Fairy Guard', 'Minuscule'],
  },
  {
    name: 'Brisk Gale',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/brisk-gale.md',
    cost: 1,
    count: 1,
    stamina: 2,
    stability: 0,
    size: '1S',
    speed: 5,
    movement: 'Fly',
    freeStrike: 1,
    immunities: ['Sonic R'],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: 2,
      R: 0,
      I: 0,
      P: 1,
    },
    text: "The gales are twisting ribbons of cloud and debris endlessly dancing in place. They disrupt the air and allow their allies to move freely.\n\n| Elemental (Air) | - | - | Signature Minion Harrier | 1 essence per minion summoned |\n|:----------:|:---------------:|:------------------------:|:-:|:-----------------------------:|\n| **1S**<br>Size | **5**<br>Speed | **2**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **Sonic R**<br>Immunity | **Fly**<br>Movement | - | **—**<br>Weakness | **Sonic**<br>Free Strike Damage Type |\n| **-2**<br>Might | **+2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+1**<br>Presence |\n\n> ⭐️ **Cutting the Air**\n>\n> The gale doesn't provoke [opportunity attacks](scc.v1:mcdm.heroes.v1/rule.combat/opportunity-attack) by moving.\n\n> ⭐️ **Whirlwind**\n>\n> When the gale is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), winds whip in their space until the end of the encounter. You or an ally that enters this space or starts their turn there can immediately [shift](scc.v1:mcdm.heroes.v1/movement/shifting) (including vertically).",
    traits: ['Cutting the Air', 'Whirlwind'],
  },
  {
    name: 'Crux of Ash',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/crux-of-ash.md',
    cost: 3,
    count: 2,
    stamina: 6,
    stability: 0,
    size: '1M',
    speed: 5,
    movement: 'Fly',
    freeStrike: 5,
    immunities: ['Fire R', 'Sonic R'],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: -2,
      R: 0,
      I: 0,
      P: 1,
    },
    text: "The crux is a curtain of billowing hot ash with an avian head. They cover their victims in a burning cloak of charcoal and soot.\n\n| Elemental (Fire, Air) | - | - | Minion Ambusher | 3 essence for two minions |\n|:-----------:|:---------------------:|:---------------:|:-:|:-------------------------:|\n| **1M**<br>Size | **5**<br>Speed | **6 \\| 6**<br>Stamina | **0**<br>Stability | **5**<br>Free Strike |\n| **Fire R, Sonic R**<br>Immunity | **Fly**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **-2**<br>Might | **-2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+1**<br>Presence |\n\n> ⭐️ **Soot Strike**\n>\n> The crux's melee [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) M < AVERAGE automatically [hide](scc.v1:mcdm.heroes.v1/feature.common.maneuvers/hide) each ally from the target until the start of the crux's next turn, until the target uses a [maneuver](scc.v1:mcdm.heroes.v1/rule.combat/turn) to clear the soot, until the crux takes damage, or until the crux is destroyed.\n\n> ⭐️ **Ashen Cloud (1 Essence)**\n>\n> When the crux is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), the area within 1 square of the crux is clouded by ash until it is dispersed by wind. You or any ally are [concealed](scc.v1:mcdm.heroes.v1/rule.combat/concealment) while occupying an affected square. An enemy can't establish [line of effect](scc.v1:mcdm.heroes.v1/rule.combat/line-of-effect) beyond the ash while occupying an affected square.",
    traits: ['Soot Strike', 'Ashen Cloud (1 Essence)'],
  },
  {
    name: 'Desolation of Sand',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/desolation-of-sand.md',
    cost: 3,
    count: 2,
    stamina: 5,
    stability: 1,
    size: '1M',
    speed: 5,
    movement: 'Burrow',
    freeStrike: 4,
    immunities: ['Sonic R'],
    weaknesses: [],
    characteristics: {
      M: 1,
      A: 2,
      R: 0,
      I: 0,
      P: -2,
    },
    text: "The desolations have vaguely humanoid sand forms with no legs. Their glass hose “arms” shift and bristle before firing high pressure streams of sand at their foes.\n\n| Elemental (Air, Earth) | - | - | Minion Hexer | 3 essence for two minions |\n|:------------------:|:----------------------:|:------------:|:-:|:-------------------------:|\n| **1M**<br>Size | **5**<br>Speed | **5 \\| 5**<br>Stamina | **1**<br>Stability | **4**<br>Free Strike |\n| **Sonic R**<br>Immunity | **Burrow**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+1**<br>Might | **+2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **-2**<br>Presence |\n\n> ⭐️ **Burying Strike**\n>\n> The desolation's [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) inflict M < AVERAGE [slowed](scc.v1:mcdm.heroes.v1/condition/slowed) (save ends). If the target is already [slowed](scc.v1:mcdm.heroes.v1/condition/slowed), then they are M < STRONG [restrained](scc.v1:mcdm.heroes.v1/condition/restrained) ([EoT](scc.v1:mcdm.heroes.v1/rule.combat/end-of-turn)).\n\n> ⭐️ **Sand Through Your Fingers**\n>\n> The desolation doesn't provoke [opportunity attacks](scc.v1:mcdm.heroes.v1/rule.combat/opportunity-attack) by moving.\n\n> ⭐️ **Shifting Sand Pit (1 Essence)**\n>\n> When the desolation is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), the area within 1 square of the desolation becomes [difficult terrain](scc.v1:mcdm.heroes.v1/movement/difficult-terrain) for enemies until the end of the encounter. You or an ally that enters the affected area can immediately [shift](scc.v1:mcdm.heroes.v1/movement/shifting) 3.",
    traits: ['Burying Strike', 'Sand Through Your Fingers', 'Shifting Sand Pit (1 Essence)'],
  },
  {
    name: 'Elemental Mote',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/elemental-mote.md',
    cost: 1,
    count: 1,
    stamina: 1,
    stability: 0,
    size: '1T',
    speed: 5,
    movement: 'Fly',
    freeStrike: 1,
    immunities: [],
    weaknesses: [],
    characteristics: {
      M: 0,
      A: 0,
      R: 0,
      I: 0,
      P: 2,
    },
    text: "This near-pure form of autonomous essence just barely maintains their form. They can shift their nature to match their surroundings.\n\n| Elemental | - | - | Signature Minion Hexer | 1 essence per minion summoned |\n|:--------------:|:---------:|:----------------------:|:-:|:-----------------------------:|\n| **1T**<br>Size | **5**<br>Speed | **1**<br>Stamina | **0**<br>Stability | **1**<br>Free Strike |\n| **—**<br>Immunity | **Fly**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **0**<br>Might | **0**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Dweomer Burst**\n>\n> When the mote is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), each enemy adjacent to the mote has a [bane](scc.v1:mcdm.heroes.v1/rule.dice/bane) on their next [strike](scc.v1:mcdm.heroes.v1/rule.combat/strike).\n\n> ⭐️ **Catalyst**\n>\n> Once per turn, the mote can transform into an adjacent allied [signature minion](scc.v1:mcdm.summoner.v1/feature.summoner.level-1/minions), maintaining their current Stamina. The minion must be reassigned to a new squad if their new name differs from the other squad members.\n>\n> Alternatively, you can spend 1 essence to transform the mote into any [signature minion](scc.v1:mcdm.summoner.v1/feature.summoner.level-1/minions) in the elemental portfolio you don't have, as if you summoned the new minion into the mote's space.",
    traits: ['Dweomer Burst', 'Catalyst'],
  },
  {
    name: 'Fire Plume',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/fire-plume.md',
    cost: 1,
    count: 1,
    stamina: 1,
    stability: 0,
    size: '1T',
    speed: 5,
    movement: '—',
    freeStrike: 2,
    immunities: ['Fire R'],
    weaknesses: [],
    characteristics: {
      M: -2,
      A: 1,
      R: 0,
      I: 0,
      P: 2,
    },
    text: "A fire plume burns so bright that their true shape is hard to discern from the flames. They sputter and spit motes of fire in high arcs.\n\n| Elemental (Fire) | - | - | Signature Minion Artillery | 1 essence per minion summoned |\n|:----------:|:----------------:|:--------------------------:|:-:|:-----------------------------:|\n| **1T**<br>Size | **5**<br>Speed | **1**<br>Stamina | **0**<br>Stability | **2**<br>Free Strike |\n| **Fire R**<br>Immunity | **—**<br>Movement | - | **—**<br>Weakness | **Fire**<br>Free Strike Damage Type |\n| **-2**<br>Might | **+1**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+2**<br>Presence |\n\n> ⭐️ **Spitfire Strike**\n>\n> The plume's ranged [free strikes](scc.v1:mcdm.heroes.v1/feature.common.main-actions/free-strike) have a distance of 10.\n\n> ⭐️ **Pyre**\n>\n> When the plume is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), their space becomes wreathed in flames until the end of the encounter. An enemy that enters this space or starts their turn there takes 2 fire damage.",
    traits: ['Spitfire Strike', 'Pyre'],
  },
  {
    name: 'Flow of Magma',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/flow-of-magma.md',
    cost: 3,
    count: 2,
    stamina: 6,
    stability: 2,
    size: '1L',
    speed: 5,
    movement: 'Climb',
    freeStrike: 4,
    immunities: ['Fire R'],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: -2,
      R: 0,
      I: 0,
      P: 1,
    },
    text: "This elemental is a long, serpentine creature of heated rock. Flows of magma drool trails of lava from their fangs after biting their prey.\n\n| Elemental (Fire, Earth) | - | - | Minion Harrier | 3 essence for two minions |\n|:-------------:|:-----------------------:|:--------------:|:-:|:-------------------------:|\n| **1L**<br>Size | **5**<br>Speed | **6 \\| 6**<br>Stamina | **2**<br>Stability | **4**<br>Free Strike |\n| **Fire R**<br>Immunity | **Climb**<br>Movement | - | **—**<br>Weakness | **Fire**<br>Free Strike Damage Type |\n| **+2**<br>Might | **-2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+1**<br>Presence |\n\n> 🏹 **Molten Strike 2d10 + R (Signature Ability)**\n>\n> | **Magic, Melee, Strike** | **[Main action](scc.v1:mcdm.heroes.v1/rule.combat/turn)** |\n> |--------------------------|----------------:|\n> | **📏 Melee 2** | **🎯 One creature or object per minion** |\n>\n> 4 fire damage; [shift](scc.v1:mcdm.heroes.v1/movement/shifting) 3\n>\n> 6 fire damage; [shift](scc.v1:mcdm.heroes.v1/movement/shifting) 4\n>\n> 8 fire damage; [shift](scc.v1:mcdm.heroes.v1/movement/shifting) 5\n>\n> **Effect:** Each square that the flow [shifts](scc.v1:mcdm.heroes.v1/movement/shifting) into becomes wreathed in flames until the start of the flow's next turn. An enemy that enters an affected square takes 2 damage.\n\n> ⭐️ **Eruption (1 Essence)**\n>\n> When the flow is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), they launch lava into an area equal to 1 + their size within 5 squares. The affected area becomes [difficult terrain](scc.v1:mcdm.heroes.v1/movement/difficult-terrain) for enemies until the end of the encounter. An enemy that enters an affected square or starts their turn there takes A < AVERAGE 4 fire damage.",
    traits: ['Molten Strike 2d10 + R (Signature Ability)', 'Eruption (1 Essence)'],
  },
  {
    name: 'Walking Boulder',
    circle: 'Storms',
    family: 'elemental',
    sourcePath: 'en/unified/md/monster/minion/summoner/elemental/statblock/walking-boulder.md',
    cost: 1,
    count: 1,
    stamina: 3,
    stability: 'R',
    size: '2',
    speed: 4,
    movement: 'Climb',
    freeStrike: 1,
    immunities: [],
    weaknesses: [],
    characteristics: {
      M: 2,
      A: -2,
      R: 0,
      I: 0,
      P: 1,
    },
    text: 'These massive clods of animated stone roll upon smaller piles of rocks that could be perceived as limbs. Walking boulders are useful for taking up space and forming barricades.\n\n| Elemental (Earth) | - | - | Signature Minion Defender | 1 essence per minion summoned |\n|:---------------:|:-----------------:|:-------------------------:|:-:|:-----------------------------:|\n| **2**<br>Size | **4**<br>Speed | **3**<br>Stamina | **R**<br>Stability | **1**<br>Free Strike |\n| **—**<br>Immunity | **Climb**<br>Movement | - | **—**<br>Weakness | **—**<br>Free Strike Damage Type |\n| **+2**<br>Might | **-2**<br>Agility | **0**<br>Reason | **0**<br>Intuition | **+1**<br>Presence |\n\n> ⭐️ **Obstruct**\n>\n> The boulder obstructs [line of effect](scc.v1:mcdm.heroes.v1/rule.combat/line-of-effect) for enemies.\n\n> ⭐️ **Pile Up (1 Essence)**\n>\n> When one or more boulders is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), they each leave behind a stone [wall](scc.v1:mcdm.heroes.v1/rule.combat/wall) equal to their size in their space until the end of the encounter.\n\n> **Traits with an Essence Cost**\n>\n> Some minion stat blocks have traits that can only be activated if you spend the [heroic resource](scc.v1:mcdm.heroes.v1/rule.resource/heroic-resource) listed in the top corner of the trait. For example, when a crux of ash is reduced to 0 [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina), you can spend 1 essence to use their Ashen Cloud trait.',
    traits: ['Obstruct', 'Pile Up (1 Essence)'],
  },
];
