// SPDX-License-Identifier: GPL-3.0-only
// A05 acceptance checks at the shared-operation level: the R04 worked examples reproduced through
// `/ability use` (real content snapshot, real Goblin Warrior instance, server dice), targeting draft
// auto-fire with per-target edges, a multi-target attack, the affordability block, the critical path
// with the allowance tracker, temporary Stamina order, Slain at zero with the encounter open,
// unsupported clauses recorded verbatim and Resolved at table, the post-roll correction as a linked
// entry, Catch Breath as a maneuver, Defend and Aid Attack, and retry idempotency. Expected numbers
// are copied from docs/roll-and-damage-resolution.md section 10; every assertion reads persisted rows
// or a query back.
//
// Dice come from the campaign's own S02 generator: `atDice` positions the stream counter at the next
// point where the two d10 produce the wanted faces, so the operation still rolls through rollDice.
import { describe, expect, test } from 'vitest';
import { api, internal } from '../../convex/_generated/api';
import type { Doc, Id } from '../../convex/_generated/dataModel';
import { generate } from '../../convex/lib/dice';
import { fromHex } from '../../convex/lib/sha256';
import { backend, storedEvents, table, type Backend } from './fixtures/table';

type Fixture = Awaited<ReturnType<typeof table>>;
type Client = Fixture['director']['client'];

const submit = (client: Client, campaignId: Id<'campaigns'>, text: string, commandId: string) =>
  client.mutation(api.commands.submit, { campaignId, text, commandId });
let n = 0;
const cid = (label: string) => `${label}-${String(++n).padStart(6, '0')}`;

const BRUTAL_SLAM = 'mcdm.heroes.v1/feature.ability.fury.level-1/brutal-slam';
const THUNDER_ROAR = 'mcdm.heroes.v1/feature.ability.fury.level-1/thunder-roar';
const GOBLIN = 'mcdm.monsters.v1/monster.goblin.statblock/goblin-warrior';

/** Positions the campaign's dice stream so the next 2d10 are `faces` (generated by S02's own DRBG). */
async function atDice(t: Backend, campaignId: Id<'campaigns'>, faces: [number, number]) {
  await t.run(async ctx => {
    let state = await ctx.db
      .query('diceStates')
      .withIndex('by_campaign', q => q.eq('campaignId', campaignId))
      .unique();
    if (!state) {
      const seed = crypto.getRandomValues(new Uint8Array(32));
      const id = await ctx.db.insert('diceStates', {
        campaignId,
        seed: [...seed].map(b => b.toString(16).padStart(2, '0')).join(''),
        counter: 0,
      });
      state = (await ctx.db.get(id))!;
    }
    const seed = fromHex(state.seed);
    const spec = [
      { id: 'd10a', sides: 10 },
      { id: 'd10b', sides: 10 },
    ];
    for (let counter = state.counter; counter < state.counter + 100000; counter++) {
      const out = generate(seed, counter, spec);
      if (out.dice[0]!.value === faces[0] && out.dice[1]!.value === faces[1]) {
        await ctx.db.patch(state._id, { counter });
        return;
      }
    }
    throw new Error('No matching dice position found.');
  });
}

async function foeRow(t: Backend, id: Id<'foes'>) {
  return (await t.run(ctx => ctx.db.get(id)))!;
}
async function heroRow(t: Backend, id: Id<'characters'>) {
  return (await t.run(ctx => ctx.db.get(id)))!;
}
async function eventById(t: Backend, campaignId: Id<'campaigns'>, id: Id<'events'>) {
  return (await storedEvents(t, campaignId)).find(e => e._id === id)!;
}
function data<T>(event: Doc<'events'>): T {
  return (event.payload as { data: T }).data;
}
async function rolls(t: Backend) {
  return t.run(ctx => ctx.db.query('rolls').take(100));
}

/**
 * Grug's fixture facts (docs/hero-fixture.md) supplied by the Director for Thorn: Might 2, Agility 2,
 * Reason 0, Intuition 1, Presence 0; Mountain +0/+0/+4; max Stamina 30, Recoveries 10; Ferocity.
 */
async function prepareHero(
  fixture: Fixture,
  options: { ferocity?: number; stamina?: number } = {},
) {
  const { director, campaignId } = fixture;
  await submit(
    director.client,
    campaignId,
    `@Thorn /hero facts might=2 agility=2 reason=0 intuition=1 presence=0 melee="+0/+0/+4" kit="Mountain" signature="Pain for Pain" resource="Ferocity" abilities=["${BRUTAL_SLAM}","${THUNDER_ROAR}"]`,
    cid('facts'),
  );
  await submit(
    director.client,
    campaignId,
    `@Thorn /adjust stamina value=${options.stamina ?? 30}`,
    cid('adj'),
  );
  await submit(director.client, campaignId, '@Thorn /adjust recoveries value=10', cid('adj'));
  await submit(
    director.client,
    campaignId,
    `@Thorn /adjust heroic-resource value=${options.ferocity ?? 0}`,
    cid('adj'),
  );
}

async function addGoblin(t: Backend, fixture: Fixture) {
  const catalog = await fixture.director.client.query(api.foes.catalog, {
    campaignId: fixture.campaignId,
  });
  expect(catalog.definitionId).toBe(GOBLIN);
  return fixture.director.client.mutation(api.foes.add, {
    campaignId: fixture.campaignId,
    definitionId: catalog.definitionId,
    commandId: cid('add'),
  });
}

/** Content, hero facts, one Goblin Warrior, combat opened with the heroes first, Thorn's turn taken. */
async function battle(
  t: Backend,
  options: { ferocity?: number; stamina?: number; goblins?: number; takeTurn?: boolean } = {},
) {
  const fixture = await table(t);
  await t.mutation(internal.content.reseed, {});
  await prepareHero(fixture, options);
  const goblins: Id<'foes'>[] = [];
  for (let i = 0; i < (options.goblins ?? 1); i++) goblins.push(await addGoblin(t, fixture));
  const { director, player, campaignId } = fixture;
  await submit(director.client, campaignId, '/combat start', cid('start'));
  await submit(director.client, campaignId, '/combat commit', cid('commit'));
  await submit(player.client, campaignId, '/combat roll', cid('roll'));
  await submit(director.client, campaignId, '/combat first side=heroes', cid('first'));
  if (options.takeTurn !== false)
    await submit(player.client, campaignId, '@Thorn /turn take', cid('take'));
  return { ...fixture, goblins, goblin: goblins[0]! };
}

describe('A05 attacks, damage, costs and common actions', () => {
  test('acceptance 1 and 2: 10.1 free strike through /ability use; retry returns the same result with no second roll or damage', async () => {
    const t = backend();
    const { player, observer, campaignId, goblin, thornId } = await battle(t);
    await atDice(t, campaignId, [4, 5]);
    const id = cid('strike');
    const used = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      id,
    );
    const event = await eventById(t, campaignId, used.eventId);
    expect(event.kind).toBe('ability.use');
    expect(event.actorName).toBe('Player');
    expect(event.dice).toEqual([
      { id: 'd10a', sides: 10, value: 4 },
      { id: 'd10b', sides: 10, value: 5 },
    ]);
    const payload = data<{
      result: {
        naturalRoll: number;
        selectedCharacteristic: string;
        characteristicValue: number;
        criticalHit: boolean;
        additionalMainActionOffered: boolean;
        targets: {
          total: number;
          tier: number;
          damage: { rolledDamage: number; kitBonus: number };
        }[];
        damageApplications: {
          staminaBefore: number;
          staminaAfter: number;
          windedAfter: boolean;
          slain: boolean;
        }[];
      };
      source: { id: string; text: string };
    }>(event);
    // 10.1: natural 9, Might selected (tie, printed order), total 11 → tier 1, damage 2 + 2 + 0 = 4.
    expect(payload.result).toMatchObject({
      naturalRoll: 9,
      selectedCharacteristic: 'M',
      characteristicValue: 2,
      criticalHit: false,
      additionalMainActionOffered: false,
    });
    expect(payload.result.targets[0]).toMatchObject({ total: 11, tier: 1 });
    expect(payload.result.targets[0]!.damage).toMatchObject({ rolledDamage: 4, kitBonus: 0 });
    expect(payload.result.damageApplications[0]).toMatchObject({
      staminaBefore: 15,
      staminaAfter: 11,
      windedAfter: false,
      slain: false,
    });
    // The verbatim source text travels with the entry.
    expect(payload.source.id).toBe(
      'mcdm.heroes.v1/feature.ability.common/melee-weapon-free-strike',
    );
    expect(payload.source.text).toContain('- **≤11:** 2 + M or A damage');
    // Persisted state: Goblin Warrior 15 → 11; journal row under the event.
    expect((await foeRow(t, goblin)).live.stamina).toBe(11);
    const changes = await t.run(ctx =>
      ctx.db
        .query('changes')
        .withIndex('by_event', q => q.eq('eventId', used.eventId))
        .take(50),
    );
    expect(changes.find(c => c.path === 'live.stamina')).toMatchObject({
      entityTable: 'foes',
      entityId: goblin,
      before: { present: true, value: 15 },
      after: { present: true, value: 11 },
    });
    // Action tracking: one main action used on Thorn's turn; the allowance shows it.
    const uses = await t.run(ctx => ctx.db.query('actionUses').take(10));
    expect(uses.map(u => [u.actionType, u.label, u.opportunityId])).toEqual([
      ['main action', 'Melee Weapon Free Strike', null],
    ]);
    const sheet = await player.client.query(api.abilities.sheet, {
      campaignId,
      actor: { kind: 'character', id: thornId, name: 'Thorn' },
    });
    expect(sheet.allowance).toEqual({
      inCombat: true,
      onTurn: true,
      mainUsed: 1,
      maneuverUsed: 0,
      extraMainOffered: 0,
    });
    expect(sheet.abilities.map(a => a.name)).toEqual([
      'Brutal Slam',
      'Thunder Roar',
      'Melee Weapon Free Strike',
      'Ranged Weapon Free Strike',
      'Catch Breath',
      'Defend',
      'Aid Attack',
    ]);
    // Retry: same command id, same result; still one roll, one event, Stamina still 11.
    expect(
      await submit(
        player.client,
        campaignId,
        `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
        id,
      ),
    ).toEqual(used);
    expect(await rolls(t)).toHaveLength(2); // the initiative d10 and this 2d10
    expect((await storedEvents(t, campaignId)).filter(e => e.kind === 'ability.use')).toHaveLength(
      1,
    );
    expect((await foeRow(t, goblin)).live.stamina).toBe(11);
    // The observer cannot attack; a player cannot act for the foe.
    await expect(
      submit(
        observer.client,
        campaignId,
        `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
        cid('obs'),
      ),
    ).rejects.toThrow();
  });

  test('acceptance 1: 10.2, 10.3 and 10.13 reproduce through the operation (kit bonus at tier 3, winded at 2, Brutal Slam rows, push recorded verbatim)', async () => {
    const t = backend();
    const { player, campaignId, goblin } = await battle(t);
    const strike = async (ability: string, faces: [number, number]) => {
      await t.run(ctx => ctx.db.patch(goblin, { live: { stamina: 15, temporaryStamina: 0 } }));
      await atDice(t, campaignId, faces);
      const used = await submit(
        player.client,
        campaignId,
        `@Thorn /ability use ability="${ability}" targets=[@{foe:${goblin}}]`,
        cid('strike'),
      );
      const event = await eventById(t, campaignId, used.eventId);
      return {
        event,
        result: data<{
          result: {
            naturalRoll: number;
            criticalHit: boolean;
            targets: {
              total: number;
              tier: number;
              damage: { rolledDamage: number };
              unresolvedClauses: string[];
            }[];
            damageApplications: { staminaAfter: number; windedAfter: boolean; slain: boolean }[];
          };
        }>(event).result,
        stamina: (await foeRow(t, goblin)).live.stamina,
      };
    };
    // 10.2: dice 6 + 7 → total 15 → tier 2, damage 7, Goblin 15 → 8.
    let r = await strike('Melee Weapon Free Strike', [6, 7]);
    expect(r.result.targets[0]).toMatchObject({ total: 15, tier: 2 });
    expect(r.result.targets[0]!.damage.rolledDamage).toBe(7);
    expect(r.stamina).toBe(8);
    // 10.3: dice 8 + 9 → total 19 → tier 3, damage 7 + 2 + 4 = 13, Goblin 15 → 2, winded, not slain, not a critical.
    r = await strike('Melee Weapon Free Strike', [8, 9]);
    expect(r.result).toMatchObject({ naturalRoll: 17, criticalHit: false });
    expect(r.result.targets[0]).toMatchObject({ total: 19, tier: 3 });
    expect(r.result.targets[0]!.damage.rolledDamage).toBe(13);
    expect(r.result.damageApplications[0]).toMatchObject({
      staminaAfter: 2,
      windedAfter: true,
      slain: false,
    });
    expect(r.stamina).toBe(2);
    expect(r.event.description).toContain('now winded');
    // 10.13 Brutal Slam: 3 + 6 → 11 → tier 1 → 5 → 10; 7 + 7 → 16 → tier 2 → 8 → 7 winded; 9 + 9 → 20 → tier 3 → 15 → 0 slain.
    r = await strike('Brutal Slam', [3, 6]);
    expect(r.result.targets[0]).toMatchObject({ total: 11, tier: 1 });
    expect(r.result.targets[0]!.damage.rolledDamage).toBe(5);
    expect(r.stamina).toBe(10);
    expect(r.result.targets[0]!.unresolvedClauses).toEqual([
      '[push](scc.v1:mcdm.heroes.v1/movement/forced-movement) 1',
    ]);
    r = await strike('Brutal Slam', [7, 7]);
    expect(r.result.targets[0]).toMatchObject({ total: 16, tier: 2 });
    expect(r.result.targets[0]!.damage.rolledDamage).toBe(8);
    expect(r.result.damageApplications[0]).toMatchObject({ staminaAfter: 7, windedAfter: true });
    r = await strike('Brutal Slam', [9, 9]);
    expect(r.result).toMatchObject({ naturalRoll: 18, criticalHit: false });
    expect(r.result.targets[0]).toMatchObject({ total: 20, tier: 3 });
    expect(r.result.targets[0]!.damage.rolledDamage).toBe(15);
    expect(r.result.damageApplications[0]).toMatchObject({
      staminaAfter: 0,
      windedAfter: true,
      slain: true,
    });
    expect(r.stamina).toBe(0);
    // A pre-fire characteristic override outside the printed set is refused (1.8).
    await expect(
      submit(
        player.client,
        campaignId,
        `@Thorn /ability use ability="Brutal Slam" targets=[@{foe:${goblin}}] characteristic=A`,
        cid('bad'),
      ),
    ).rejects.toThrow('not permitted');
  });

  test('acceptance 2: draft flow — per-target edge entered, ability selected, target toggled auto-fires once with the edge recorded; the draft clears', async () => {
    const t = backend();
    const { player, campaignId, goblin, thornId } = await battle(t);
    await submit(
      player.client,
      campaignId,
      `@Thorn /target modifier target=@{foe:${goblin}} edges=1`,
      cid('mod'),
    );
    const selected = await submit(
      player.client,
      campaignId,
      '@Thorn /ability select ability="Melee Weapon Free Strike"',
      cid('sel'),
    );
    expect((await eventById(t, campaignId, selected.eventId)).kind).toBe('target.draft');
    let drafts = await player.client.query(api.targets.drafts, { campaignId });
    expect(drafts.mine).toMatchObject({
      abilityId: 'mcdm.heroes.v1/feature.ability.common/melee-weapon-free-strike',
      targets: [],
      modifiers: { [`foe:${goblin}`]: { edges: 1, banes: 0 } },
    });
    // The Director sees the player's draft as an indicator only after targets are selected.
    await atDice(t, campaignId, [6, 6]);
    const fired = await submit(
      player.client,
      campaignId,
      `/target toggle target=@{foe:${goblin}}`,
      cid('toggle'),
    );
    const event = await eventById(t, campaignId, fired.eventId);
    expect(event.kind).toBe('ability.use');
    // Natural 12 with one edge: 12 + 2 + 2 = 16 → tier 2 (10.5 row 2); damage 7; Goblin 15 → 8.
    const result = data<{
      targets: { edges: number; banes: number }[];
      result: {
        targets: { edgeBane: { edges: number; modifier: number }; total: number; tier: number }[];
      };
    }>(event);
    expect(result.targets).toEqual([
      { target: { kind: 'foe', id: goblin, name: 'Goblin Warrior' }, edges: 1, banes: 0 },
    ]);
    expect(result.result.targets[0]).toMatchObject({
      edgeBane: { edges: 1, modifier: 2 },
      total: 16,
      tier: 2,
    });
    expect(event.dice!.map(d => d.value)).toEqual([6, 6]);
    expect((await foeRow(t, goblin)).live.stamina).toBe(8);
    drafts = await player.client.query(api.targets.drafts, { campaignId });
    expect(drafts.mine).toBeNull();
    // Selecting the same ability twice cancels; a self-only ability fires on selection (Defend).
    await submit(
      player.client,
      campaignId,
      '@Thorn /ability select ability="Brutal Slam"',
      cid('sel'),
    );
    await submit(
      player.client,
      campaignId,
      '@Thorn /ability select ability="Brutal Slam"',
      cid('sel'),
    );
    expect((await player.client.query(api.targets.drafts, { campaignId })).mine).toBeNull();
    const defend = await submit(
      player.client,
      campaignId,
      '@Thorn /ability select ability=Defend',
      cid('sel'),
    );
    const defendEvent = await eventById(t, campaignId, defend.eventId);
    expect(defendEvent.kind).toBe('ability.recorded');
    expect(defendEvent.description).toContain('Rule warning: Thorn already used a main action');
    expect(data<{ source: { text: string } }>(defendEvent).source.text).toContain(
      'ability rolls](scc.v1:mcdm.heroes.v1/rule.dice/ability-roll) made against them have a double',
    );
    const sheet = await player.client.query(api.abilities.sheet, {
      campaignId,
      actor: { kind: 'character', id: thornId, name: 'Thorn' },
    });
    expect(sheet.allowance.mainUsed).toBe(2);
  });

  test('acceptance 3 and 4: 10.6 Thunder Roar on three Goblin Warriors with different counts; Ferocity 6 → 1 in the same command unit; 10.11 blocked with Ferocity 2', async () => {
    const t = backend();
    const { player, director, campaignId, goblins, thornId } = await battle(t, {
      ferocity: 2,
      goblins: 3,
    });
    const [w1, w2, w3] = goblins as [Id<'foes'>, Id<'foes'>, Id<'foes'>];
    const command = `@Thorn /ability use ability="Thunder Roar" targets=[@{foe:${w1}},@{foe:${w2}},@{foe:${w3}}] edges=[1,0,0] banes=[0,2,0]`;
    const rollsBefore = (await rolls(t)).length;
    // 10.11: Ferocity 2 < cost 5 → blocked for the player and for the Director alike.
    for (const client of [player.client, director.client]) {
      const blocked = await submit(client, campaignId, command, cid('blocked'));
      const event = await eventById(t, campaignId, blocked.eventId);
      expect(event.kind).toBe('ability.blocked');
      expect(event.dice).toBeUndefined();
      expect(data<{ blocked: unknown }>(event).blocked).toEqual({
        kind: 'blocked',
        abilityId: THUNDER_ROAR,
        actorId: thornId,
        cost: { resource: 'ferocity', amount: 5 },
        poolBefore: 2,
        reason: 'Ferocity 2 < cost 5',
      });
    }
    expect((await rolls(t)).length).toBe(rollsBefore);
    expect((await heroRow(t, thornId)).liveState!.heroicResource.current).toBe(2);
    expect(await t.run(ctx => ctx.db.query('actionUses').take(5))).toEqual([]);
    for (const id of goblins) expect((await foeRow(t, id)).live.stamina).toBe(15);
    // With Ferocity 6: debit and roll appear in one command unit.
    await submit(director.client, campaignId, '@Thorn /adjust heroic-resource value=6', cid('adj'));
    await atDice(t, campaignId, [7, 6]);
    const used = await submit(player.client, campaignId, command, cid('roar'));
    const event = await eventById(t, campaignId, used.eventId);
    expect(event.kind).toBe('ability.use');
    const result = data<{
      result: {
        naturalRoll: number;
        criticalHit: boolean;
        cost: unknown;
        targets: {
          targetId: string;
          total: number;
          tier: number;
          damage: { rolledDamage: number };
          unresolvedClauses: string[];
        }[];
        damageApplications: {
          targetId: string;
          staminaAfter: number;
          windedAfter: boolean;
          slain: boolean;
        }[];
        manualResolutions: { sourceClause: string }[];
      };
    }>(event).result;
    expect(result.cost).toEqual({
      resource: 'ferocity',
      amount: 5,
      waived: false,
      before: 6,
      after: 1,
    });
    expect(result.naturalRoll).toBe(13);
    expect(result.criticalHit).toBe(false);
    expect(result.targets.map(x => [x.total, x.tier, x.damage.rolledDamage])).toEqual([
      [17, 3, 17],
      [15, 1, 6],
      [15, 2, 9],
    ]);
    expect(result.damageApplications.map(d => [d.staminaAfter, d.windedAfter, d.slain])).toEqual([
      [-2, true, true],
      [9, false, false],
      [6, true, false],
    ]);
    expect(result.targets.map(x => x.unresolvedClauses)).toEqual([
      ['[push](scc.v1:mcdm.heroes.v1/movement/forced-movement) 6'],
      ['[push](scc.v1:mcdm.heroes.v1/movement/forced-movement) 2'],
      ['[push](scc.v1:mcdm.heroes.v1/movement/forced-movement) 4'],
    ]);
    expect(result.manualResolutions.map(m => m.sourceClause)).toEqual([
      'Effect: The targets are [force moved](scc.v1:mcdm.heroes.v1/movement/forced-movement) one at a time, starting with the target nearest to you, and can be [pushed](scc.v1:mcdm.heroes.v1/movement/forced-movement) into other targets in the same line.',
    ]);
    expect((await heroRow(t, thornId)).liveState!.heroicResource.current).toBe(1);
    expect(await Promise.all(goblins.map(async id => (await foeRow(t, id)).live.stamina))).toEqual([
      -2, 9, 6,
    ]);
    const journal = await t.run(ctx =>
      ctx.db
        .query('changes')
        .withIndex('by_event', q => q.eq('eventId', used.eventId))
        .take(50),
    );
    expect(journal.map(c => c.path)).toEqual(
      expect.arrayContaining(['liveState.heroicResource.current', 'live.stamina']),
    );
    expect(journal[0]!.path).toBe('liveState.heroicResource.current');
    // Warrior 1 is Slain; the encounter stays committed and open.
    const view = (await director.client.query(api.encounters.current, { campaignId }))!;
    expect(view.status).toBe('committed');
    expect(view.groups.flatMap(g => g.entries).find(e => e.actor.id === w1)!.slain).toBe(true);
  });

  test('acceptance 5: natural 20 logs a critical, applies tier 3 and offers an extra main action; a second main action consumes it; a third warns', async () => {
    const t = backend();
    const { player, campaignId, goblin, thornId } = await battle(t);
    await atDice(t, campaignId, [10, 10]);
    const crit = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      cid('crit'),
    );
    const event = await eventById(t, campaignId, crit.eventId);
    const result = data<{
      result: {
        naturalRoll: number;
        criticalHit: boolean;
        additionalMainActionOffered: boolean;
        targets: { total: number; tier: number; damage: { rolledDamage: number } }[];
      };
    }>(event).result;
    // 10.4: natural 20, total 22, tier 3, damage 13, Goblin 15 → 2.
    expect(result).toMatchObject({
      naturalRoll: 20,
      criticalHit: true,
      additionalMainActionOffered: true,
    });
    expect(result.targets[0]).toMatchObject({ total: 22, tier: 3 });
    expect(result.targets[0]!.damage.rolledDamage).toBe(13);
    expect((await foeRow(t, goblin)).live.stamina).toBe(2);
    expect(event.description).toContain('Critical hit');
    const opportunities = await t.run(ctx => ctx.db.query('actionOpportunities').take(5));
    expect(opportunities).toHaveLength(1);
    expect(opportunities[0]).toMatchObject({
      status: 'offered',
      sourceEventId: crit.eventId,
      usedEventId: null,
    });
    const actor = { kind: 'character' as const, id: thornId, name: 'Thorn' };
    let sheet = await player.client.query(api.abilities.sheet, { campaignId, actor });
    expect(sheet.allowance).toMatchObject({ mainUsed: 1, extraMainOffered: 1 });
    // Not taking it has no effect: the offer simply remains recorded. Taking a second main action succeeds
    // without a warning and consumes the opportunity.
    await atDice(t, campaignId, [4, 5]);
    const second = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      cid('second'),
    );
    const secondEvent = await eventById(t, campaignId, second.eventId);
    expect(secondEvent.description).not.toContain('Rule warning');
    expect((await t.run(ctx => ctx.db.get(opportunities[0]!._id)))!).toMatchObject({
      status: 'used',
      usedEventId: second.eventId,
    });
    sheet = await player.client.query(api.abilities.sheet, { campaignId, actor });
    expect(sheet.allowance).toMatchObject({ mainUsed: 2, extraMainOffered: 0 });
    // A third main action is a warned departure, never a block.
    await atDice(t, campaignId, [4, 5]);
    const third = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      cid('third'),
    );
    expect((await eventById(t, campaignId, third.eventId)).description).toContain(
      'Rule warning: Thorn already used a main action this turn',
    );
    // The opportunity is not duplicated by a retry of the critical command.
    await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      cid('crit').replace(/\d+$/, String(n - 3).padStart(6, '0')),
    );
    expect(await t.run(ctx => ctx.db.query('actionOpportunities').take(5))).toHaveLength(1);
  });

  test('acceptance 6: Spear Charge tier 3 (5 damage) against 3 temporary Stamina and 20 Stamina leaves 0 and 18 in one event; the creature free strike takes temporary Stamina first (10.14)', async () => {
    const t = backend();
    const { director, player, campaignId, goblin, thornId } = await battle(t, { stamina: 20 });
    await submit(
      director.client,
      campaignId,
      '@Thorn /adjust temporary-stamina value=3',
      cid('adj'),
    );
    await submit(player.client, campaignId, '@Thorn /turn end', cid('end'));
    await submit(director.client, campaignId, `@{foe:${goblin}} /turn take`, cid('take'));
    // Goblin Warrior "Power Roll + 2": dice 8 + 8 → natural 16 + 2 = 18 → tier 3 → "5 damage".
    await atDice(t, campaignId, [8, 8]);
    const used = await submit(
      director.client,
      campaignId,
      `@{foe:${goblin}} /ability use ability="Spear Charge" targets=[@Thorn]`,
      cid('spear'),
    );
    const event = await eventById(t, campaignId, used.eventId);
    const payload = data<{
      result: {
        characteristicValue: number;
        selectedCharacteristic?: string;
        criticalHit: boolean;
        targets: { total: number; tier: number; damage: { rolledDamage: number } }[];
        damageApplications: {
          absorbedByTemporaryStamina: number;
          temporaryStaminaAfter: number;
          staminaDelta: number;
          staminaAfter: number;
          dying: boolean;
        }[];
      };
      source: { text: string; supporting: { id: string }[] };
    }>(event);
    expect(payload.result.characteristicValue).toBe(2);
    expect(payload.result.selectedCharacteristic).toBeUndefined();
    expect(payload.result.targets[0]).toMatchObject({ total: 18, tier: 3 });
    expect(payload.result.targets[0]!.damage.rolledDamage).toBe(5);
    expect(payload.result.damageApplications[0]).toMatchObject({
      absorbedByTemporaryStamina: 3,
      temporaryStaminaAfter: 0,
      staminaDelta: 2,
      staminaAfter: 18,
      dying: false,
    });
    const live = (await heroRow(t, thornId)).liveState!;
    expect([live.temporaryStamina, live.stamina]).toEqual([0, 18]);
    // Both changes are journaled under the one event.
    const journal = await t.run(ctx =>
      ctx.db
        .query('changes')
        .withIndex('by_event', q => q.eq('eventId', used.eventId))
        .take(50),
    );
    expect(journal.map(c => [c.path, c.before, c.after])).toEqual(
      expect.arrayContaining([
        ['liveState.stamina', { present: true, value: 20 }, { present: true, value: 18 }],
        ['liveState.temporaryStamina', { present: true, value: 3 }, { present: true, value: 0 }],
      ]),
    );
    // The stat-block ability text is the blockquote; the whole stat block supports it.
    expect(payload.source.text.startsWith('> 🗡 **Spear Charge (Signature Ability)**')).toBe(true);
    expect(payload.source.supporting[0]!.id).toBe(GOBLIN);
    // 10.14: the creature free strike never rolls; with 3 temporary Stamina, temporary 2, Stamina unchanged.
    await submit(
      director.client,
      campaignId,
      '@Thorn /adjust temporary-stamina value=3',
      cid('adj'),
    );
    const rollsBefore = (await rolls(t)).length;
    const free = await submit(
      director.client,
      campaignId,
      `@{foe:${goblin}} /ability use ability="Free Strike" targets=[@Thorn]`,
      cid('free'),
    );
    const freeEvent = await eventById(t, campaignId, free.eventId);
    expect(freeEvent.dice).toBeUndefined();
    expect((await rolls(t)).length).toBe(rollsBefore);
    expect(freeEvent.description).toContain('no roll; Free Strike 1');
    const after = (await heroRow(t, thornId)).liveState!;
    expect([after.temporaryStamina, after.stamina]).toEqual([2, 18]);
    // A player cannot act for the foe.
    await expect(
      submit(
        player.client,
        campaignId,
        `@{foe:${goblin}} /ability use ability="Free Strike" targets=[@Thorn]`,
        cid('p'),
      ),
    ).rejects.toThrow('do not control');
  });

  test('acceptance 7: reducing the foe to 0 shows Slain in the roster and the encounter remains open; a Malice ability debits the shared pool', async () => {
    const t = backend();
    const { director, player, observer, campaignId, goblin } = await battle(t);
    await t.run(ctx => ctx.db.patch(goblin, { live: { stamina: 4, temporaryStamina: 0 } }));
    await atDice(t, campaignId, [4, 5]);
    await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      cid('kill'),
    );
    expect((await foeRow(t, goblin)).live.stamina).toBe(0);
    for (const client of [director.client, player.client, observer.client]) {
      const roster = await client.query(api.table.roster, { campaignId });
      expect(roster.foes[0]!.slain).toBe(true);
    }
    const encounter = (await t.run(ctx => ctx.db.query('encounters').first()))!;
    expect(encounter.status).toBe('committed');
    expect(encounter.archivedAt).toBeNull();
    // Slain warning on the foe's turn; Bury the Point costs 2 Malice from the shared pool.
    await submit(player.client, campaignId, '@Thorn /turn end', cid('end'));
    await submit(director.client, campaignId, '/adjust malice value=3', cid('adj'));
    const took = await submit(
      director.client,
      campaignId,
      `@{foe:${goblin}} /turn take`,
      cid('take'),
    );
    expect((await eventById(t, campaignId, took.eventId)).description).toContain('Slain');
    await atDice(t, campaignId, [3, 3]);
    const bury = await submit(
      director.client,
      campaignId,
      `@{foe:${goblin}} /ability use ability="Bury the Point" targets=[@Thorn]`,
      cid('bury'),
    );
    const buryEvent = await eventById(t, campaignId, bury.eventId);
    // Natural 6 + 2 = 8 → tier 1: "5 damage; M < 0 bleeding (save ends)" — the potency clause is unresolved.
    const result = data<{
      result: {
        cost: unknown;
        targets: { total: number; tier: number; unresolvedClauses: string[] }[];
      };
    }>(buryEvent).result;
    expect(result.cost).toEqual({
      resource: 'malice',
      amount: 2,
      waived: false,
      before: 3,
      after: 1,
    });
    expect(result.targets[0]).toMatchObject({ total: 8, tier: 1 });
    expect(result.targets[0]!.unresolvedClauses).toEqual([
      'M < 0 [bleeding](scc.v1:mcdm.heroes.v1/condition/bleeding) (save ends)',
    ]);
    expect((await t.run(ctx => ctx.db.get(campaignId)))!.malice).toBe(1);
    // Malice 1 < cost 2: blocked for the Director too.
    const blocked = await submit(
      director.client,
      campaignId,
      `@{foe:${goblin}} /ability use ability="Bury the Point" targets=[@Thorn]`,
      cid('bury'),
    );
    expect((await eventById(t, campaignId, blocked.eventId)).kind).toBe('ability.blocked');
    expect((await t.run(ctx => ctx.db.get(campaignId)))!.malice).toBe(1);
  });

  test('acceptance 8: an unsupported clause appears verbatim; Director Resolved at table records the disposition without changing state and cannot be recorded twice', async () => {
    const t = backend();
    const { director, player, campaignId, goblin } = await battle(t);
    await atDice(t, campaignId, [7, 7]);
    const used = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Brutal Slam" targets=[@{foe:${goblin}}]`,
      cid('slam'),
    );
    const event = await eventById(t, campaignId, used.eventId);
    const clause = '[push](scc.v1:mcdm.heroes.v1/movement/forced-movement) 2';
    expect(event.description).toContain(`unresolved: "${clause}"`);
    expect((await foeRow(t, goblin)).live.stamina).toBe(7);
    // A player cannot mark it; the Director can, once.
    await expect(
      submit(
        player.client,
        campaignId,
        `/ability resolved event="${used.eventId}" clause="${clause}" target=@{foe:${goblin}}`,
        cid('p'),
      ),
    ).rejects.toThrow('Director');
    const resolved = await submit(
      director.client,
      campaignId,
      `/ability resolved event="${used.eventId}" clause="${clause}" target=@{foe:${goblin}} note="pushed 2 squares on the mat"`,
      cid('resolved'),
    );
    const resolvedEvent = await eventById(t, campaignId, resolved.eventId);
    expect(resolvedEvent.kind).toBe('ability.resolved-at-table');
    expect(resolvedEvent.causeEventId).toBe(used.eventId);
    expect(resolvedEvent.actorName).toBe('Director');
    expect((await foeRow(t, goblin)).live.stamina).toBe(7);
    const changes = await t.run(ctx =>
      ctx.db
        .query('changes')
        .withIndex('by_event', q => q.eq('eventId', resolved.eventId))
        .take(10),
    );
    expect(changes.map(c => c.entityTable)).toEqual(['abilityResults']);
    const results = await director.client.query(api.abilities.results, { campaignId });
    expect(results[0]!.targets[0]!.dispositions).toEqual([
      { clause, eventId: resolved.eventId, note: 'pushed 2 squares on the mat' },
    ]);
    await expect(
      submit(
        director.client,
        campaignId,
        `/ability resolved event="${used.eventId}" clause="${clause}" target=@{foe:${goblin}}`,
        cid('again'),
      ),
    ).rejects.toThrow('already marked');
    await expect(
      submit(
        director.client,
        campaignId,
        `/ability resolved event="${used.eventId}" clause="push 9" target=@{foe:${goblin}}`,
        cid('wrong'),
      ),
    ).rejects.toThrow('not an unresolved clause');
    // The original event is untouched.
    expect((await eventById(t, campaignId, used.eventId)).description).toBe(event.description);
  });

  test('acceptance 9: 10.10 post-roll Add bane changes tier and damage with the same dice as a linked correction; the original event is unchanged; a further correction needs the rewind first', async () => {
    const t = backend();
    const { director, player, observer, campaignId, goblin } = await battle(t);
    await atDice(t, campaignId, [8, 2]);
    const used = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Melee Weapon Free Strike" targets=[@{foe:${goblin}}]`,
      cid('strike'),
    );
    const original = await eventById(t, campaignId, used.eventId);
    expect(
      data<{ result: { targets: { total: number; tier: number }[] } }>(original).result.targets[0],
    ).toMatchObject({ total: 12, tier: 2 });
    expect((await foeRow(t, goblin)).live.stamina).toBe(8);
    const rollsBefore = (await rolls(t)).length;
    // A06 window: the acting player may correct their own latest attack; an observer may not.
    await expect(
      submit(
        observer.client,
        campaignId,
        `/ability correct event="${used.eventId}" target=@{foe:${goblin}} edges=0 banes=1`,
        cid('o'),
      ),
    ).rejects.toThrow();
    const corrected = await submit(
      player.client,
      campaignId,
      `/ability correct event="${used.eventId}" target=@{foe:${goblin}} edges=0 banes=1`,
      cid('correct'),
    );
    const correction = await eventById(t, campaignId, corrected.eventId);
    expect(correction.kind).toBe('correction.ability');
    expect(correction.causeEventId).toBe(used.eventId);
    expect(correction.dice).toBeUndefined();
    expect((await rolls(t)).length).toBe(rollsBefore);
    const payload = data<{
      correction: {
        dice: { d10a: number; d10b: number };
        before: { tier: number; damage: { rolledDamage: number } };
        after: { tier: number; total: number; damage: { rolledDamage: number } };
        staminaReconciliationDelta: number;
        damageAfter: { staminaAfter: number; windedAfter: boolean };
      };
    }>(correction).correction;
    // Same dice; total 10 → tier 1; damage 4; reconciliation +3 → Stamina 8 → 11; winded stays false.
    expect(payload.dice).toEqual({ d10a: 8, d10b: 2 });
    expect(payload.before).toMatchObject({ tier: 2 });
    expect(payload.before.damage.rolledDamage).toBe(7);
    expect(payload.after).toMatchObject({ total: 10, tier: 1 });
    expect(payload.after.damage.rolledDamage).toBe(4);
    expect(payload.staminaReconciliationDelta).toBe(3);
    expect(payload.damageAfter).toMatchObject({ staminaAfter: 11, windedAfter: false });
    expect((await foeRow(t, goblin)).live.stamina).toBe(11);
    // The original event is unchanged; the effective record carries the correction.
    expect(await eventById(t, campaignId, used.eventId)).toEqual(original);
    const results = await director.client.query(api.abilities.results, { campaignId });
    expect(results[0]!.targets[0]).toMatchObject({ edges: 0, banes: 1 });
    expect(results[0]!.correctionEventIds).toEqual([corrected.eventId]);
    // The correction is its own unit (kind correction.*): a further correction of the older attack
    // needs the sequential rewind first (A06 window), for the Director as well. Removal of the bane
    // restoring tier 2 / 7 damage / Stamina 8 is verified in tests/resolve.test.ts (10.10).
    await expect(
      submit(
        director.client,
        campaignId,
        `/ability correct event="${used.eventId}" target=@{foe:${goblin}} edges=0 banes=0`,
        cid('restore'),
      ),
    ).rejects.toThrow('rewind');
    expect((await foeRow(t, goblin)).live.stamina).toBe(11);
    // Player view: the foe's Stamina numbers are hidden under the default bar display; the arithmetic is not.
    const forPlayer = await player.client.query(api.events.list, { campaignId });
    const seen = forPlayer.events.find(e => e.id === corrected.eventId)!;
    expect(seen.description).not.toContain('Stamina 8 → 11');
    expect(seen.description).toContain('reconciliation +3 Stamina');
    expect(JSON.stringify(seen.payload)).not.toContain('"staminaAfter"');
    const seenUse = forPlayer.events.find(e => e.id === used.eventId)!;
    expect(JSON.stringify(seenUse.payload)).not.toContain('"staminaAfter"');
    expect(JSON.stringify(seenUse.payload)).toContain('"rolledDamage":7');
  });

  test('Catch Breath in combat is a maneuver with action tracking (10.9); FreePlay use spends no maneuver; Aid Attack is recorded with its text and a maneuver warning', async () => {
    const t = backend();
    const { director, player, campaignId, goblin, thornId } = await battle(t, { stamina: 22 });
    const used = await submit(
      player.client,
      campaignId,
      '@Thorn /ability use ability="Catch Breath"',
      cid('cb'),
    );
    const event = await eventById(t, campaignId, used.eventId);
    expect(event.kind).toBe('hero.catch-breath');
    // 10.9: Stamina 22 + 10 = 32 > 30 → 30, healed 8, capApplied (Q-R-3); Recoveries 10 → 9.
    expect(data<{ result: unknown }>(event).result).toMatchObject({
      recoveryValue: 10,
      recoveriesBefore: 10,
      recoveriesAfter: 9,
      staminaBefore: 22,
      staminaAfter: 30,
      healed: 8,
      capApplied: true,
      uncertainty: 'Q-R-3',
    });
    const live = (await heroRow(t, thornId)).liveState!;
    expect([live.stamina, live.recoveries]).toEqual([30, 9]);
    const uses = await t.run(ctx => ctx.db.query('actionUses').take(5));
    expect(uses.map(u => [u.actionType, u.label])).toEqual([['maneuver', 'Catch Breath']]);
    const aid = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Aid Attack" targets=[@{foe:${goblin}}]`,
      cid('aid'),
    );
    const aidEvent = await eventById(t, campaignId, aid.eventId);
    expect(aidEvent.kind).toBe('ability.recorded');
    expect(aidEvent.description).toContain('Rule warning: Thorn already used a maneuver this turn');
    expect(
      data<{ source: { text: string }; targets: { name: string }[] }>(aidEvent).source.text,
    ).toContain('gains an [edge](scc.v1:mcdm.heroes.v1/rule.dice/edge)');
    expect(data<{ targets: { name: string }[] }>(aidEvent).targets[0]!.name).toBe('Goblin Warrior');
    // A foe cannot Catch Breath: no Recovery pool → blocked, nothing spent.
    const foeCatch = await submit(
      director.client,
      campaignId,
      `@{foe:${goblin}} /ability use ability="Catch Breath"`,
      cid('foe-cb'),
    );
    expect((await eventById(t, campaignId, foeCatch.eventId)).kind).toBe('ability.blocked');
    // Third maneuver warns again (advisory); the sheet counts two.
    const sheet = await player.client.query(api.abilities.sheet, {
      campaignId,
      actor: { kind: 'character', id: thornId, name: 'Thorn' },
    });
    expect(sheet.allowance).toMatchObject({ maneuverUsed: 2, mainUsed: 0 });
  });

  test('FreePlay: Ferocity cost waived outside combat with no debit; second use warns; no action tracking rows', async () => {
    const t = backend();
    const fixture = await table(t);
    await t.mutation(internal.content.reseed, {});
    await prepareHero(fixture, { ferocity: 2 });
    const goblin = await addGoblin(t, fixture);
    const { player, campaignId, thornId } = fixture;
    await atDice(t, campaignId, [7, 6]);
    const first = await submit(
      player.client,
      campaignId,
      `@Thorn /ability use ability="Thunder Roar" targets=[@{foe:${goblin}}]`,
      cid('fp'),
    );
    const event = await eventById(t, campaignId, first.eventId);
    expect(event.kind).toBe('ability.use');
    expect(data<{ result: { cost: unknown; warnings: string[] } }>(event).result.cost).toEqual({
      resource: 'ferocity',
      amount: 5,
      waived: true,
      before: 2,
      after: 2,
    });
    expect((await heroRow(t, thornId)).liveState!.heroicResource.current).toBe(2);
    expect(await t.run(ctx => ctx.db.query('actionUses').take(5))).toEqual([]);
    // Natural 13 + 2 = 15 → tier 2 → "9 damage" (no kit bonus at tier 2): Goblin 15 → 6.
    expect((await foeRow(t, goblin)).live.stamina).toBe(6);
  });

  test('every A05 operation is registered and discoverable', async () => {
    const t = backend();
    const { director, campaignId } = await table(t);
    const listed = await director.client.query(api.commands.list, { campaignId });
    const ids = listed.map(op => op.id);
    expect(ids).toEqual(
      expect.arrayContaining([
        'ability.select',
        'target.toggle',
        'target.modifier',
        'selection.cancel',
        'ability.fire',
        'ability.use',
        'ability.correct',
        'ability.resolved',
        'hero.facts',
      ]),
    );
    expect(listed.find(op => op.id === 'ability.use')!.syntax).toBe(
      '@Actor /ability use ability=… [targets=…] [edges=…] [banes=…] [characteristic=…] [fromDraft=…]',
    );
    expect(listed.find(op => op.id === 'ability.resolved')!.roles).toEqual(['director']);
  });
});
